version: '2'
services:
  meshcentral:
    container_name: meshcentral
    image: ghcr.io/gurucomputing/meshcentral-docker:latest
    restart: "always"
    volumes:
      - ${CONFIG}:/meshcentral/meshcentral-data
      - ${FILES}:/meshcentral/meshcentral-files
      - ${BACK}:/meshcentral/meshcentral-backup
      - /etc/localtime:/etc/localtime:ro
    ports:
      - ${PORT8}:80
      - ${PORT4}:443
